### ISSUE TITLE
Unable to find client.profile for authenticated user

### ISSUE THREAD

**Issue by gandhinikita** [hexgnu/linkedin#264]
When I am doing client.profile(:id => 'xxxx') its working fine but for my own profile i.e client.profile it is giving error inkedIn::Errors::NotFoundError (404): Not Found
I don't know what I am doing wrong

Also it is giving error "Could not find person based on: ~\"

Please help

**Comment by hexgnu** [comment]
Not entirely sure could you please post what code you are using?

**Comment by arthurtofani** [comment]
+1

**Comment by nilanjenator** [comment]
I folllowed the example on Ubuntu and get the same error with client.profile

LinkedIn::Errors::NotFoundError: (404): Not Found
	from /var/lib/gems/2.1.0/gems/linkedin-1.1.0/lib/linked_in/helpers/request.rb:54:in `raise_errors'
	from /var/lib/gems/2.1.0/gems/linkedin-1.1.0/lib/linked_in/helpers/request.rb:16:in `get'
	from /var/lib/gems/2.1.0/gems/linkedin-1.1.0/lib/linked_in/api/query_helpers.rb:27:in `simple_query'
	from /var/lib/gems/2.1.0/gems/linkedin-1.1.0/lib/linked_in/api/people.rb:22:in `profile'
	from (irb):15
	from /usr/bin/irb:11:in `<main>'
